config/routes.rb
Rails.application.routes.draw do
 root 'billboards#index'

 resources :billboards

  resources :artists do 
    resources :songs
  end

  get 'new_billboard_song/:id', to: 'billboards#new_song', as: 'new_billboard_song'
	post 'add_billboard_song/:id/:song_id', to: 'billboards#add_song', as: 'add_billboard_song'
  delete 'remove_billboard_song/:id/:song_id', to: 'billboards#remove_song', as: 'remove_billboard_song'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :songs, dependent: :destroy

    validates_presence_of :name
end

app/models/billboard.rb
class Billboard < ApplicationRecord
    has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :billboard,  optional: true
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  def index
    @artists = Artist.all
  end

  def show

  end

  def new
    @artist = Artist.new
    render partial: 'form'
  end

  def create
    @artist = Artist.new(set_params)
    if @artist.save
      redirect_to artists_path
    else
      render :new
    end
  end

  def edit
    render partial: 'form'
  end

  def update
    if @artist.update(set_params)
      redirect_to artists_path
    else
      render :edit
    end
  end

  def destroy 
    @artist.destroy
    redirect_to artists_path
  end

  private 
  def set_artist
    @artist = Artist.find(params[:id])
  end
  def set_params
    params.require(:artist).permit(:name)
  end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :edit, :update, :destroy, :add_song]
  
  def index
    @billboards = Billboard.all
  end

  def show
  end

  def new
    @billboard = Billboard.new
    render partial: 'form'
  end
  
  def create
    @billboard = Billboard.new(set_params)
    if @billboard.save
      redirect_to billboards_path
    else
      render :new
    end
  end

  def edit
    render partial: 'form'
  end

  def update
    if @billboard.update(set_params)
      redirect_to billboards_path
    else 
      render :new
    end
  end

  def destroy
    @billboard.destroy
    redirect_to billboards_path
  end

  def new_song
    @billboard = Billboard.find(params[:id])
    @songs = Song.all.where(billboard_id: nil)
  end

  def add_song
    @billboard.songs << Song.find(params[:song_id])
    redirect_to billboard_path(@billboard)
  end

  def remove_song
    @billboard = Billboard.find(params[:id])
    Song.find(params[:song_id]).update(billboard_id: nil)
    redirect_to billboard_path(@billboard)
  end




  private 
  def set_billboard
    @billboard = Billboard.find(params[:id])
  end

  def set_params
    params.require(:billboard).permit(:name)
  end
 
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = @artist.songs
  end

  def show
  end

  def new
    @song = @artist.songs.new
    render partial: 'form'
  end

  def create
    @song = @artist.songs.new(set_params)

    if @song.save
      redirect_to artist_songs_path
    else
      render :new
    end

  end

  def edit
    render partial: 'form'
  end

  def update
    if @song.update(set_params)
      redirect_to artist_songs_path
    else
      render :edit
    end

  end

  def destroy
    @song.destroy
    redirect_to artist_songs_path(@artist)
  end

  private

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end

  def set_song
    @song = Song.find(params[:id])
  end

  def set_params
    params.require(:song).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist do |f|%>
<%= f.label :name %>
<%= f.text_field :name, required: true, autofocus: true  %>

<%= f.submit %>
<% end %>

<%= link_to 'Back', artists_path%>

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1>Artists#index</h1>
<% @artists.each do |artist|%>
<h2><%= artist.name%><h2>
<%= link_to 'Show songs', artist_songs_path(artist)%>
<%= link_to 'Edit songs', edit_artist_path(artist)%>
<%= link_to 'Delete Artist', artist, method: :delete%>
<% end %>

<h2>Add New Artist</h2>
<%= link_to 'New Artist', new_artist_path%>
<br>
<%= link_to 'Back', billboards_path%>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

app/views/billboards/_form.html.erb
<%= form_for @billboard do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>

  <%= f.submit %>
<% end %>

app/views/billboards/edit.html.erb
<h1>Billboards#edit</h1>
<p>Find me in app/views/billboards/edit.html.erb</p>

app/views/billboards/index.html.erb
<h1>Billboards</h1>
<% @billboards.each do |billboard|%>
<h2><%= billboard.name %> </h2>
<%= link_to 'Show billboard', billboard_path(billboard)%>
<%= link_to 'Edit billboard', edit_billboard_path(billboard)%>
<%= link_to 'Delete billboard', billboard,  method: :delete%>
<% end %>

<h1>Create New Billboard</h1>
<%= link_to 'New billboard', new_billboard_path%>
<h1>Artists</h1>
<%= link_to 'Artist', artists_path%>

app/views/billboards/new.html.erb
<h1>Billboards#new</h1>
<p>Find me in app/views/billboards/new.html.erb</p>

app/views/billboards/new_song.html.erb
<h1>New Billboard page</h1>
<h1><%= @billboard.name %> </h1>

	<% @songs.each do |song| %>
	  <li>
	    <%= link_to song.name, add_billboard_song_path(@billboard, song), method: :post %>
	  </li>
	  <hr />
	<% end %>


<%= link_to 'Back', billboards_path%>

app/views/billboards/show.html.erb
<h1><%= @billboard.name %></h1>
<% if @billboard.songs.any? %>
  <% @billboard.songs.each do |song| %>
    <p><%= song.name %></p>
     <%= link_to 'Remove From billboard', remove_billboard_song_path(@billboard, song), method: :delete %>
  <% end %>
<% end %>

<%= link_to 'Add Song', new_billboard_song_path(@billboard) %> |
<%= link_to 'Back', billboards_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicBillboards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for [@artist, @song] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>

  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1><%= "#{@artist.name}"%></h1>
<% @songs.each do |song| %>
  <h2><%= song.name %></h2>
  <%= link_to 'Song Info', artist_song_path(@artist, song) %>
   <%= link_to 'Edit Song', edit_artist_song_path(@artist, song) %>
    <%= link_to 'remove Song', [@artist, song], method: :delete %>

  
<% end %>

<h1>Create New Item</h1>
  <%= link_to 'Create New Song', new_artist_song_path %>
  <br>
   <br>
    <%= link_to 'Back', artists_path %>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>